-- =====================================================================
-- ATTENDANCE -- unique constraint on (employee_id, attendance_date)
-- =====================================================================
-- check_in() (app/attendance/services.py) currently guards against a
-- double check-in with a plain check-then-insert:
--
--     if attendance_repo.find_one({employee_id, attendance_date}):
--         bad_request("You have already checked in today.")
--     ...
--     attendance_repo.create(payload)
--
-- That's a classic TOCTOU race: two check-in requests for the same
-- employee arriving close enough together (a double-tap before the
-- button's disabled state re-renders, a mobile network retry, someone
-- checking in from two tabs/devices) can both read "no row yet" before
-- either one writes, and both then insert -- producing two attendance
-- rows for the same employee on the same day. Nothing in the schema
-- today stops that.
--
-- This is the actual fix: a unique constraint makes the DB itself the
-- single source of truth for "only one attendance row per employee per
-- day", no matter how many requests race each other or which app
-- server/worker handles them. check_in() has a matching code change to
-- catch the resulting unique-violation and turn it into the same
-- friendly "You have already checked in today." response instead of a
-- raw 500 -- see the unique-violation catch added around
-- attendance_repo.create(payload) there.
--
-- IMPORTANT -- run this check FIRST. If any employee already has more
-- than one attendance row for the same date (from a race that already
-- happened before this migration existed), the ALTER below will fail
-- until those duplicates are manually reviewed and merged/deleted:
--
--   select employee_id, attendance_date, count(*)
--   from attendance
--   group by employee_id, attendance_date
--   having count(*) > 1;
--
-- If that returns any rows, resolve them (decide which row is correct,
-- delete or merge the other(s)) before running the ALTER below.

alter table attendance
  add constraint attendance_employee_date_unique
  unique (employee_id, attendance_date);